name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  release:
    types:
      - published
  schedule:
    - cron: "0 21 * * *"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.18.2

      - name: Check code formatting
        run: crystal tool format --check

      - name: Install dependencies
        run: shards install

      - name: Run tests
        run: crystal spec
